### ISSUE TITLE
Deezer integration doesn't work

### ISSUE THREAD

**Issue by CheckMatt** [tiliado/nuvola-app-deezer#1]
I've just installed Nuvola Player 3 and Nuvola Deezer Integration.
When I open NP, I can connect to my Deezer account, I can listen to a song but I cannot switch to an other song or stop. When I click on Play Button in the Gnome Dialog, I get this error :+1: 

> Error during call of Nuvola.actions.emit: Function 'Nuvola.actions.emit' failed. file:///home/matthieu/.local> /share/nuvolaplayer3/web_apps/deezer/integrate.js:126: TypeError: undefined is not an object (evaluating 'window.playercontrol.$btnPlay.click')

> The application might not function properly.

I suppose Deezer change his code and integration.js isn't up to date ?

Thanks :)

**Comment by fenryxo** [comment]
> I suppose Deezer change his code and integration.js isn't up to date ?

Yes, exactly. I'll take a look at it tomorrow :-)

**Comment by fenryxo** [comment]
The fix has landed to master branch and is also available in the repository. Feel free to reopen this ticket if the issue persists.

**Comment by CheckMatt** [comment]
It's working, thanks !
