### ISSUE TITLE
[WebKitGTK bug] Deezer Family secondary profiles don't work

### ISSUE THREAD

**Issue by ontherunvaro** [tiliado/nuvola-app-deezer#10]
**This issue is caused by an instability of Flash plugin in WebKitGTK library, which is tracked at tiliado/nuvolaruntime#354. Refer to that ticket for more information and updates.**

---

In an account with a [Deezer Family](https://support.deezer.com/hc/en-gb/articles/115002459285-Deezer-Family) subscription, everything works as expected for the main profile, but when trying to switch to a secondary one, the page hangs for several seconds and then this alert appears:
![image](https://user-images.githubusercontent.com/8677743/27331177-b69d1884-55bc-11e7-9dbd-b503db46fde4.png)

If "Close" is clicked, it appears as if the profile has been switched correctly, but music playback fails.

The song appears on the "playing" square on the lower left corner, and MPRIS information is sent correctly, but no sound is played, the progress bar doesn't move and the play/pause icon stays in the "Play" mode, hinting that it's not actually playing anything.

I'm sending 
[a log of opening the Deezer app, switching profile (with hang and alert) and trying to play some songs.](https://github.com/tiliado/nuvola-app-deezer/files/1088044/nuvola-deezer-family-log.txt)

System: Ubuntu 16.04 X86_64, with Linux 4.8.0-54

**Comment by fenryxo** [comment]
Hello @ontherunvaro. It looks as [Flash crash](https://bugs.webkit.org/show_bug.cgi?id=172450) according to the log.

**Comment by ontherunvaro** [comment]
So, any workaround? e.g. different version of Flash or something?

**Comment by fenryxo** [comment]
I tried to find one the last weekend but no luck yet.

**Comment by fenryxo** [comment]
Still no luck. [I've asked for help](https://lists.webkit.org/pipermail/webkit-gtk/2017-June/003098.html).

**Comment by fenryxo** [comment]
A workaround is available in [Nuvola 4.5](https://medium.com/nuvola-news/nuvola-4-5-released-a16ff727981e#35cc).

**Comment by fenryxo** [comment]
Closing as upstream bug. See tiliado/nuvolaruntime#354 for details.
