### ISSUE TITLE
HTML5 Player

### ISSUE THREAD

**Issue by fenryxo** [tiliado/nuvola-app-deezer#12]
* It is possible to turn the HTML5 on in Nuvola 4.6.7.
* But it throws "NotSupportedError: The operation is not supported." in http://e-cdn-files.deezer.com/cache/js/vendor.b72d21e1146c5cca1ec4.js:43898
* Deezer support request sent.

Deezer Support Request

> I'm considering purchasing Deezer subscription for me & my family but I cannot currently use Deezer without the Flash plugin, and that's a deal-breaker for me. In addition, I develop a specialized web browser that integrates Deezer web player with Linux desktop features, and some users expressed their interest in Flash-free playback.
>
> I use a WebKitGTK-based browser which shares the core with Safari 11 ("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/604.1 (KHTML, like Gecko) Version/11.0 Safari/604.1 Nuvola/4.6.1"). The https://support.deezer.com/hc/en-gb/articles/115004370249-Common-Fixes-for-your-Browser web page mentions that your HTML5 Player should work with Safari 10+ ("If you are using Chrome 55+ or Safari 10+ then you can activate our HTML5 player as a work around for many Flash Player-related issues.") and I can, indeed, turn HTML5 Player on in my browser.
>
>However, when I click the play button, the only thing I get is "NotSupportedError: The operation is not supported." coming from http://e-cdn-files.deezer.com/cache/js/vendor.b72d21e1146c5cca1ec4.js:43898. While I understand you don't have resources to support Linux users and non-mainstream web browsers, I would appreciate if your engineers could spare a few minutes to answer my questions so that I could discuss this issue with WebKitGTK developers and maybe make Deezer's HTML5 Player work.
>
>1) Does Deezer use any open source JavaScript library for HTML5 audio playback or an in-house solution?
>
> 2) Do you have any idea what may have caused that NotSupportedError? There is no useful call stack in WebKit WebInspector and the JavaScript code is minified.
>
> 3) What are API requirements of the player? MediaSource.isTypeSupported("audio/mpeg") returns true in my browser and MSE works fine with Microsoft Groove and BBC iPlayer, for example. Is any of AudioContext, AudioPannerNode, OfflineAudioContext, ArrayBuffer, ReadableStream, SourceBuffer, TransformStream, Uint8Array, and WritableStream also required?
>
> Thank you in advance for your reply.
>
> Best regards,
>
> Jiri Janousek
>
> P.S. Since my browser is an open-source project, the summary of this conversation will be included in its documentation.

**Comment by fenryxo** [comment]
Deezer's Reply 6 Aug, 13:50 CEST

> [...]
>
> I have passed on your message,I cannot promise that you will get an answer though. We are working on HTML5 for more browsers at he moment.
>
> Please bear with us until this can be used on more than Chrome and Safari.
>
> Please don't hesitate to contact us should you require any further assistance.

**Comment by fenryxo** [comment]
Deezer HTML5 player works in [ValaCEF](https://github.com/tiliado/valacef)

**Comment by Evpok** [comment]
Do you want some testing on that ?

**Comment by fenryxo** [comment]
Hello @Evpok. Thanks for your interest, but no testing is required at this stage. I'll ping you once ValaCEF is integrated into Nuvola. Then a lot of testing will be required.

**Comment by fenryxo** [comment]
Blog post: [Status of Chromium-based Port of Nuvola](https://medium.com/nuvola-news/nuvola-chromium-port-status-3b1648b29c77)

**Comment by fenryxo** [comment]
>  _Users with Nuvola Basic/Premium/Patron account will be invited to test development builds soon._
> -- [Status of Chromium-based Port of Nuvola](https://medium.com/nuvola-news/nuvola-chromium-port-status-3b1648b29c77)

All Nuvola Patron & Premium user have been invited to test Nuvola with working Chromium backend, Nuvola Basic users will follow in a week.

**Comment by fenryxo** [comment]
>>  _Users with Nuvola Basic/Premium/Patron account will be invited to test development builds soon._
>> -- [Status of Chromium-based Port of Nuvola](https://medium.com/nuvola-news/nuvola-chromium-port-status-3b1648b29c77)
>
> All Nuvola Patron & Premium user have been invited to test Nuvola with working Chromium backend, Nuvola Basic users will follow in a week.

Nuvola Basic users have also been invited.

**Comment by fenryxo** [comment]
Released.
