### ISSUE TITLE
Deezer New Look - keyboard shortcuts does not work

### ISSUE THREAD

**Issue by IgorKvasn** [tiliado/nuvola-app-deezer#15]
I just switched to Deezer's new look (they also call it Deezer Beta apparently) and keyboard shortcuts in Nuvola stopped working (I tried only pause/play shortcut that I use the most).
Once I switched back to the old look, shortcuts work again.

You can activate new look in _Account Settings_ -> _Deezer Labs_ -> activate feature _Try a new look_

Nuvola script version: 3.0.9 (9-g30dcb32)
Nuvola Apps Runtime: 4.12.77 (77-g3cacb5e)

**Comment by fenryxo** [comment]
Hello @IgorKvasn. Thanks for reporting the issue. I'll look at it.

**Comment by Evpok** [comment]
More generally, Nuvola's playback control (in the tray icon and via MPRIS) are unavailable (plasma 5.13.90)

**Comment by fenryxo** [comment]
This issue was fixed in **Nuvola 4.12.89** & **Deezer script 3.0.14**. You can update flatpaks with *GNOME Software* >= 3.22 or run `flatpak update --system; flatpak update --user` in a terminal.

*Keep this ticket open until the fix is officially announced.*

**Comment by fenryxo** [comment]
Announced in Update 10: [Nuvola Integrates Repeat & Shuffle Status, Adjusts to New Deezer Design, And More](https://medium.com/nuvola-news/nuvola-integrates-repeat-shuffle-status-adjusts-to-new-deezer-design-and-more-397d3bc1e03a)
