### ISSUE TITLE
Dezzer have a new web app!

### ISSUE THREAD

**Issue by pedroSBastos** [tiliado/nuvola-app-deezer#17]
Nuvola app dosen't support the new Deezer web app. Notifications, Next Song, Previous Song etc... dosen't work.

**Comment by fenryxo** [comment]
Hello @pedroSBastos. This should be fixed in Deezer script 3.0.15. Run `flatpak update --system; flatpak update --user` to make sure all your Nuvola packages are up-to-date.

**Comment by fenryxo** [comment]
If the issue is reproducible with the latest Nuvola, report the issue here: https://github.com/tiliado/nuvolaruntime/issues/new/choose
