### ISSUE TITLE
Title and album track are sometimes #document

### ISSUE THREAD

**Issue by CheckMatt** [tiliado/nuvola-app-deezer#2]
Thanks to the commit 9a72fec294c3806001c58e183e6f2c6161e6941e, I can now listen to a song and the media integration is working.

But there's still a bug regarding the track title, artist and album. Each second, the track title is alternatively the good title and "#document". It provokes a notification in permanence because the title or the artist changed.

By the way, we can see on the screenshots that the album name is "null"...

![capture d ecran de 2015-01-16 11 26 40](https://cloud.githubusercontent.com/assets/2353766/5774846/b9d84136-9d72-11e4-815b-95d037681440.png)
![capture d ecran de 2015-01-16 11 26 41](https://cloud.githubusercontent.com/assets/2353766/5774845/b9d827a0-9d72-11e4-9673-dd77bed674fd.png)

Thanks !

**Comment by fenryxo** [comment]
Hi. Thanks for taking time to report this issue. I need more information to investigate it further.

1. Could you translate the text in the screenshots to English?
2. Could you post a screenshot of a Developer's sidebar? (Click gear button on the right side of a toolbar and toggle on Show sidebar.
3. I cannot reproduce the issue, so I need to know an address of a page the issue occurs on. Go any page that causes troubles and copy here output of the following command.

```
grep last_uri ~/.config/nuvolaplayer3/apps_data/deezer/config.json
```

> By the way, we can see on the screenshots that the album name is "null"...

That's OK, Deezer's web interface doesn't contain album name.

**Comment by fenryxo** [comment]
Also copy eher debug output from terminal, especially lines with ``[Runner:INFO     Nuvola] developersidebar.vala:132: ``

```
$ nuvolaplayer3 -D -a deezer
...
[Runner:INFO     Nuvola] developersidebar.vala:132: Song a{smv} {'title': @mv <'Boulevard Of Broken Dreams (Feat. John Gallagher Jr., Rebecca Naomi Jones, Stark Sands, Company)'>, 'artist': <'Green Day'>, 'album': <@mv nothing>, 'artworkLocation': <'http://cdn-images.deezer.com/images/cover/f2be03540082c9ca0ec5e4995859f0ea/250x250.jpg'>, 'artworkFile': <@mv nothing>, 'baseActions': <[<'toggle-play'>, <'play'>, <'pause'>, <'prev-song'>, <'next-song'>]>, 'extraActions': <@av []>, 'state': <'unknown'>}
[Runner:INFO     Nuvola] developersidebar.vala:132: Song a{smv} {'title': @mv <'Boulevard Of Broken Dreams (Feat. John Gallagher Jr., Rebecca Naomi Jones, Stark Sands, Company)'>, 'artist': <'Green Day'>, 'album': <@mv nothing>, 'artworkLocation': <'http://cdn-images.deezer.com/images/cover/f2be03540082c9ca0ec5e4995859f0ea/250x250.jpg'>, 'artworkFile': <@mv nothing>, 'baseActions': <[<'toggle-play'>, <'play'>, <'pause'>, <'prev-song'>, <'next-song'>]>, 'extraActions': <@av []>, 'state': <'paused'>}
...
```

**Comment by CheckMatt** [comment]
Hi, thanks taking the time to answer !

1. That's not complicated ;)
    - « Deezer - Lecture en cours » means « Deezer - Playing ».
    - « Pomme C » is the song title. « par #document » means « by #document » (normally, it should be the artist, but here's the problem !).
    - « dans Album inconnu » means « in unknown album ».

2. To show you the alternance, I prepared a screencast : [](http://youtu.be/tRQFY_i3aV0)

3. 
```
[matthieu@pc-de-matthieu ~]$ grep last_uri ~/.config/nuvolaplayer3/apps_data/deezer/config.json
    "last_uri" : "http://www.deezer.com/tops/track"
```
On this page, the bug appears with the song « Uptown Funk », but it doesn't appear with « Prayer in C ».

4. [](http://paste.awesom.eu/lQB1&ln)

If you need more, you can ask me !

**Comment by fenryxo** [comment]
Could you try out Deezer integration 2.2?

**Comment by CheckMatt** [comment]
Good job, it's now working ! I have no more undesirable notifications.
