### ISSUE TITLE
Songs titles are not visible

### ISSUE THREAD

**Issue by Reylak** [tiliado/nuvola-app-deezer#3]
I'm running on ArchLinux, and using the Git packages : nuvolaplayer-git and nuvola-app-deezer-git.

The title of every song is not visible in Nuvola in any view (artist, album, EP, etc.). Similarly, focusing the line of a song doesn't show the buttons to share, etc. The song number is visible though, as well as the icon for the lyrics, and the line gets darker when focused as expected. Everything is displaying fine anywhere else.

![2015-08-24_15 53 34](https://cloud.githubusercontent.com/assets/162009/9441598/5db43ab0-4a77-11e5-837a-3572a0bfb7ff.png)
(as you can see I'm running a French interface, if that may have any influence)

The console output doesn't show anything relevant to me, the only warning I get when actually playing music is
> [Runner:WARNING  Nuvola] Notifications.vala:138: Unable to show notification: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files

I also got the in-app warnings about not finding a GStreamer MP3 decoder, but the songs are playing fine nonetheless.
And I also got the warning about finding multiple Flash Player Versions. I have flashplugin (and lib32 equivalent) v.11.2.xxx, which is the last official one from Adobe ; and chromium-pepper-flash-dev 16.0.xxx, which is an open equivalent working properly with Firefox.

Anyway, thank you for your work on Nuvola! The PepperFlash plugin is currently crashing with the newest version of Firefox, and Chrome is eating away my memory when I need it for work so Nuvola is a great alternative.

**Comment by fenryxo** [comment]
Hello. Thanks for taking the time to report your issue. I need more information to investigate it further:

* Debugging output from terminal as described in [Bug Reporting Guidelines](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines).
* Does the issue occur also in GNOME Web/Epiphany browser?
* Does the issue occur also if you switch to English language?

I will take a look at this issue more in [September 2015](https://github.com/tiliado/nuvolaplayer.project/issues/7) as funds for [August 2015](https://github.com/tiliado/nuvolaplayer.project/issues/5) have been exhausted.

**Comment by Reylak** [comment]
Ahah I feel dumb, _the song titles are perfectly readable now_.
I'm not sure of how your player works, but it might be due to me _updating my flash player_ (freshplayer-plugin, relying on chromium-pepper-flash-dev as mentionned above), which was failing since Firefox update. Updating this Fresh Player fixed Flash applets on Firefox, so it might have fixed this issue as well.
The other thing that changed is the connection. I was under a company proxy the first time, with a very poor connection quality (although it was enough for audio streaming).

So that's it, everything is fine ^^ Sorry for the bad report and thank you for your answer,.

**Comment by fenryxo** [comment]
No problem, happy listening!
