### ISSUE TITLE
GNOME Shell 3.16 Notification controls not working

### ISSUE THREAD

**Issue by phatina** [tiliado/nuvola-app-deezer#4]
I can't play, pause, etc music from Deezer from notification area in GNOME Shell 3.16.

I am using `nuvolaplayer3-deezer-2.3-1.fc22.x86_64` plugin.

**Note:** This works when started for the first time; later, it's not functional. I can only see play button and 2 gray buttons for track skipping.

**Comment by fenryxo** [comment]
Hello @phatina. Thanks for taking the time to report this issue. Notifications have been reworked in GNOME 3.16, so it's no surprise that Nuvola Player notification controls are broken :-( Could you provide debugging output from terminal to the point when playback controls are not functional? See [Bug Reporting Guidelines](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines) for details.
