### ISSUE TITLE
readme.md file never explain how to add deezer app on nuovaplayer3

### ISSUE THREAD

**Issue by jerome-diver** [tiliado/nuvola-app-deezer#9]
Hi,
I do install nuovaplayer3 (novaruntime new named...) on archlinux
Then i install this nuova-app-deezer (so, nuovasdk and python-pip and scour as dependencies), all is well installed.
But now, ok... and then ? how to use it with nuovaplayer3 ? I failed to find any information about that.
Please, could you tell me more around that ? I may supposed to know, but i don't.

**Comment by fenryxo** [comment]
Hello @jerome-diver. The recommended way to use the Deezer nuvola app on Arch Linux is to use [the genuine flatpak builds](https://nuvola.tiliado.eu/#!app:deezer!archlinux!) and [launch Deezer from a desktop launcher](https://tiliado.github.io/nuvolaplayer/documentation/4/explore.html#explore-gnome).

![Launch Deezer](https://tiliado.github.io/nuvolaplayer/documentation/images/3.0/gnome/gnome_activities_deezer.png)

In case of third-party builds such as AUR packages, there should also be a desktop launcher of Deezer app. If there isn't any, either Nuvola or Deezer were not installed properly.

**Comment by jerome-diver** [comment]
Hello @fenryxo,
thanks for answer.
OS is running with Xfce4. And before of that, i installed aur packages nuvolaplayer3-git, and deezer app who failed. the launcher from menu bar execute same command 
`nuvolaplayer3` -a deezer`
i install nuvolaplayer (not git) from aur packages (i had to modify the pkgbuild for make it running and find good sha256sum), and then your application (clone from git, then do what have to do).
so first of all, then i start command:
`nuvolaplayer3` -a deezer`
from terminal, it said that there is no deezer application.
Also, i can see in the git repos from where i install that there is a .dektop file.
There is also the Deezer application launcher on menu of wfce4 desktop (not the same than before, becasue there is yours icon).
When i click on it, it said "Failed to execute command "nuvola -a deezer"
sure... there is no nuvola command. the command is nuvolaplayer3. But nuvolaplayer3 -a deezer doesn't work same.
maybe i have to do something and reconstruct after write somewhere to use nuvolaplayer3 instead of nuvola ?

**Comment by fenryxo** [comment]
Ok, I'm closing this issue for now. If you return to AUR builds, please specify the exact version of Nuvola, Diorite and Deezer as well as the build flags used to compile these components.

**Comment by jerome-diver** [comment]
sorry, but i'm still confuse.
I do exactly wht is explain on your links (and uninstall from aur packages).
Now i read that i need to paid a rent for be able to have a kind of "premium" access on this interface (or a kind of "patron status"... but how ? paid a rent again ?) app for be able to connect on a rented deezer music web site... that's it ? (if that's it... just tell me)
so i can not use the player for free ? or i not understand maybe...

**Comment by fenryxo** [comment]
There are several variants of Nuvola which differ in provided support and availability.

* You can use **Nuvola 3.0.x Stable Releases** for free. The latest version 3.0.8 was released on April 15th, 2017. We provide support for Ubuntu, Debian and Fedora users. No support is guaranteed for Arch Linux as we don't provide any packages for this distribution.
* You can use **Nuvola 4.x Rolling Releases** for free if you build them from source code, but no support is guaranteed in this case. The latest version 4.4 was released on May 27, 2017.
* The genuine **flatpak builds of Nuvola 4.x Rolling Releases** are currently available only to Premium/Patron users who support Nuvola Apps project financially (monthly subscription). We provide support for Ubuntu, Debian, Fedora, elementaryOS and Arch Linux users of these builds.
* **Nuvola 5.x** (to be released later this year) will be free in the basic version for everyone, but there will be extra features for Premium/Patron users.
